##
# Jekyll config
##
port:         8080
pygments:     false
pagination:   10
markdown:     rdiscount
permalink:    /:year/:month/:day/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - tmp
include:
  - assets
  - .well-known

##
# Global Site config
##
title:        "Forty-Two"
url:          "http://jasonroelofs.com"

disqus:
  shortname: "jasonroelofs"

author:
  name: "Jason Roelofs"
  email: "jasongroelofs@gmail.com"
  github: "jasonroelofs"

projects:
  - name: SimpleAWS
    slug: simple_aws
    github_url: https://github.com/jasonroelofs/simple_aws
    description:
      "Small, simple, and forward compatible AWS communication library"
    website: http://rubydoc.info/github/jasonroelofs/simple_aws/master/frames
    install_url: https://rubygems.org/gems/simple_aws

  - name: Rice
    slug: rice
    github_url: https://github.com/jasonroelofs/rice
    description:
      "Ruby Interface for C++ Extensions. Expose your C++ classes to Ruby through a simple DSL<br/><br/>Mailing list is at <a href=\"mailto:rice@librelist.com\">rice@librelist.com</a>. Your first email will be used for registration and discarded.<br/>View the <a href=\"http://librelist.com/browser/rice/\">mailing list archives</a>."
    website: http://rice.rubyforge.org
    install_url: https://rubygems.org/gems/rice

  - name: rbgccxml
    slug: rbgccxml
    github_url: https://github.com/jasonroelofs/rbgccxml
    description:
      "Ruby library to parse and query C++ header files using GCCXML"
    website: http://rbplusplus.rubyforge.org/rbgccxml
    install_url: https://rubygems.org/gems/rbgccxml

  - name: rb++
    slug: rbplusplus
    github_url: https://github.com/jasonroelofs/rbplusplus
    description:
      "Combines rbgccxml and rice to automatically generate Ruby extensions from C++ code"
    website: http://rbplusplus.rubyforge.org
    install_url: https://rubygems.org/gems/rbplusplus

  - name: gccxml_gem
    slug: gccxml_gem
    github_url: https://github.com/jasonroelofs/gccxml_gem
    description:
      "Ruby wrapper around the GCC-XML library. Includes binary installs of GCC-XML"
    website: http://rubygems.org/gems/gccxml_gem
    install_url: https://rubygems.org/gems/gccxml_gem

  - name: RaidIt
    slug: raidit
    github_url: https://github.com/jasonroelofs/raidit
    description:
      "MMO focused calendar tool for scheduling player, guild, or server events"

  - name: Slartibartfast
    slug: slartibartfast
    github_url: https://github.com/jasonroelofs/slartibartfast
    description:
      "Space-based exploration game. An experiment in game design and development. Currently written in Go."
