# baseURL = "https://jasonroelofs.com/"
baseURL = "https://jasonroelofs.github.io/"
languageCode = "en-us"
title = "Jason Roelofs"

[Params]
  LeftSections = ["articles"]
  RightSections = ["series", "projects", "talks"]
